# Generated by Django 4.1.6 on 2023-03-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Demenagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_depart", models.DateField()),
                ("date_arrivee", models.DateField()),
                ("metres_cube", models.IntegerField()),
                ("cout", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
