# Generated by Django 4.1.6 on 2023-03-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_trans", "0002_employee_remove_demenagement_cout_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MissionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("date_depart", models.DateField()),
                ("date_arrivee", models.DateField()),
                ("distance", models.IntegerField()),
                ("lieu_depart", models.CharField(max_length=100)),
                ("lieu_arrivee", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Demenagement",
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
