# Generated by Django 4.1.6 on 2023-03-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_trans", "0004_employee_mission_delete_missionmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="mission",
            old_name="arrival_date",
            new_name="date_arrivee",
        ),
        migrations.RenameField(
            model_name="mission",
            old_name="departure_date",
            new_name="date_depart",
        ),
        migrations.RenameField(
            model_name="mission",
            old_name="arrival_location",
            new_name="lieu_arrivee",
        ),
        migrations.RenameField(
            model_name="mission",
            old_name="departure_location",
            new_name="lieu_depart",
        ),
        migrations.RenameField(
            model_name="mission",
            old_name="name",
            new_name="nom",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="employees",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="extra_charges",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="km_travelled",
        ),
        migrations.AddField(
            model_name="mission",
            name="distance",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
