# Generated by Django 4.1.6 on 2023-03-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_trans", "0006_employee_delete_employe_delete_mission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="address",
            new_name="first_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="email",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="phone",
        ),
        migrations.AddField(
            model_name="employee",
            name="last_name",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
