# Generated by Django 4.1.6 on 2023-03-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_trans", "0008_mission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="departure_date",
            field=models.DateField(default=None),
        ),
    ]
