# Generated by Django 4.1.6 on 2023-03-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_trans", "0010_alter_mission_arrival_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="departure_location",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
