# Generated by Django 4.1.6 on 2023-03-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_trans", "0011_alter_mission_departure_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="arrival_date",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="mission",
            name="arrival_location",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="mission",
            name="departure_date",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="mission",
            name="extra_charges",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mission",
            name="km_travelled",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
