# Generated by Django 4.1.2 on 2023-03-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_trans", "0012_alter_mission_arrival_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mission",
            name="arrival_date",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="arrival_location",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="departure_date",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="departure_location",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="extra_charges",
        ),
        migrations.AddField(
            model_name="mission",
            name="end_date",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="mission",
            name="end_location",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="mission",
            name="end_time",
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name="mission",
            name="start_date",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="mission",
            name="start_location",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="mission",
            name="start_time",
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="mission",
            name="km_travelled",
            field=models.IntegerField(default=None),
        ),
    ]
