# Generated by Django 4.1.2 on 2023-03-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_trans", "0013_remove_mission_arrival_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="mission",
            name="end_time",
            field=models.TimeField(),
        ),
    ]
