# Generated by Django 4.1.2 on 2023-03-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_trans", "0014_alter_mission_end_date_alter_mission_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mission",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
