# Generated by Django 4.1.2 on 2023-03-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_trans", "0015_alter_mission_end_date_alter_mission_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="end_location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="mission",
            name="km_travelled",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="mission",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="mission",
            name="start_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="mission",
            name="start_location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="mission",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
