# Generated by Django 4.1.2 on 2023-03-21 18:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_trans", "0016_alter_mission_end_location_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Mission",
        ),
    ]
