# Generated by Django 4.1.2 on 2023-03-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_trans", "0019_mission_facture_fraissupplementaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("moving", "Moving"),
                    ("cocolis", "Cocolis"),
                    ("categorie1", "Categorie1"),
                    ("categorie2", "Categorie2"),
                    ("categorie3", "Categorie3"),
                    ("extrat", "Extrat"),
                    ("fret", "Fret"),
                    ("particulier", "Particulier"),
                    ("odd", "Odd"),
                ],
                default="moving",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="hotel",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="mission",
            name="location",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="mission",
            name="peage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="mission",
            name="volume",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="mission",
            name="lieu_arrivee",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="mission",
            name="lieu_depart",
            field=models.CharField(max_length=255),
        ),
    ]
